apiVersion: v1
kind: Service
metadata:
  name: sccb-circuit-breaker
  labels:
    poc: circuit-breaker-spring-cloud
spec:
  selector:
    app: sccb-circuit-breaker
  ports:
    - port: 80
      targetPort: 8080
