apiVersion: v1
kind: Service
metadata:
  name: r4j-circuit-breaker
  labels:
    poc: circuit-breaker-java
spec:
  selector:
    app: r4j-circuit-breaker
  ports:
    - port: 80
      targetPort: 8080
