apiVersion: v1
kind: Service
metadata:
  name: dotnet-circuit-breaker
  labels:
    poc: circuit-breaker-dotnet
spec:
  selector:
    app: dotnet-circuit-breaker
  ports:
    - port: 80
      targetPort: 8080
